/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pac1.Sach;
import pac1.User;

/**
 *
 * @author sony
 */
public class LichSu extends MyPanel {
    /**
     * Creates new form muon
     */
    public LichSu() {
        super();
        initComponents();
        jComboBox1.addItem("Mượn");
        jComboBox1.addItem("Trả");
        jComboBox1.addItem("Mượn & Trả");
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etMaso = new javax.swing.JTextField();
        etTensach = new javax.swing.JTextField();
        etMathanhvien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        etTennguoimuon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý lịch sử");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã số sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã thành viên");

        etMaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etMasoActionPerformed(evt);
            }
        });
        etMaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                etMasoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etMasoKeyReleased(evt);
            }
        });

        etTensach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etTensachKeyReleased(evt);
            }
        });

        etMathanhvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etMathanhvienKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tên người mượn");

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Loại sách", "NXB", "Số lượng", "Đã cho mượn", "Số sách còn"
            }
        ));
        jScrollPane1.setViewportView(tbSach);

        etTennguoimuon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etTennguoimuonKeyReleased(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etMaso, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(etTensach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etTennguoimuon, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(etMathanhvien))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etMathanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etMaso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etTennguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etTensach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int check =0;
        String masach = etMaso.getText().toUpperCase();
        String mathanhvien = etMathanhvien.getText().toUpperCase();
        
        //Kiểm tra đầu vào mã sách
        if(getSach(masach)!=null || masach.equals("")){
            check ++;
        } 
        //Kiểm tra đầu vào user
        if(getUser(mathanhvien)!=null || mathanhvien.equals(""))
                check ++;
        if(check==2){
            loadData();
        }else
            JOptionPane.showMessageDialog(this, "Bạn đã nhập sai thông tin. Xin vui lòng kiểm tra lại");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void etTennguoimuonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTennguoimuonKeyReleased
        // TODO add your handling code here:
        String nguoimuon = etTennguoimuon.getText().toUpperCase();
        etMathanhvien.setText("");
        for (User user1 : user) {
            if (user1.getTennguoidung().toUpperCase().equals(nguoimuon)) {
                etMathanhvien.setText(user1.getManguoidung());
                break;
            }
        }
    }//GEN-LAST:event_etTennguoimuonKeyReleased

    private void etMathanhvienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMathanhvienKeyReleased
        // TODO add your handling code here:
        String mathanhvien = etMathanhvien.getText().toUpperCase();
        etTennguoimuon.setText("");
        for (User user1 : user) {
            if (user1.getManguoidung().toUpperCase().equals(mathanhvien)) {
                etTennguoimuon.setText(user1.getTennguoidung());
                break;
            }
        }
    }//GEN-LAST:event_etMathanhvienKeyReleased

    private void etTensachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTensachKeyReleased
        // TODO add your handling code here:
        String tensach = etTensach.getText().toUpperCase();
        etMaso.setText("");
        for (Sach book1 : book) {
            if (book1.getTensach().toUpperCase().equals(tensach)) {
                etMaso.setText(book1.getMasach());
                break;
            }
        }
    }//GEN-LAST:event_etTensachKeyReleased

    private void etMasoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMasoKeyReleased
        // TODO add your handling code here:
        String masach = etMaso.getText().toUpperCase();
        etTensach.setText("");
        for (Sach book1 : book) {
            if (book1.getMasach().toUpperCase().equals(masach)) {
                etTensach.setText(book1.getTensach());
                break;
            }
        }
    }//GEN-LAST:event_etMasoKeyReleased

    private void etMasoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMasoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_etMasoKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void etMasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etMasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etMasoActionPerformed
        
    
    @Override
    protected void loadData(){
        String sql="SELECT ",sql1="";
        
        if (!etMaso.getText().equals("") && !etMathanhvien.getText().equals(""))
            sql1 += "AND id_user='"+etMathanhvien.getText()+"' AND ma_sach = '"+etMaso.getText()+"' ";
        else if (etMaso.getText().equals("") && !etMathanhvien.getText().equals(""))
            sql1 += "AND id_user='"+etMathanhvien.getText()+"' ";
        else if (!etMaso.getText().equals("") && etMathanhvien.getText().equals(""))
            sql1 += "AND ma_sach = '"+etMaso.getText()+"' ";
       
        Vector data = new Vector();
        Vector cols = new Vector();

        try {
        cols.addElement("ID User");
        cols.addElement("Mã sách");
        if (jComboBox1.getSelectedItem().equals("Mượn")){
            cols.addElement("Ngày mượn");
            cols.addElement("Số lượng");
            cols.addElement("Số lượng chưa trả");
            cols.addElement("Tiền cọc");
            cols.addElement("Trạng thái");
            sql += "* from muon Where 1 " + sql1 + " order by ngay_muon";
             System.out.println(sql);
                ResultSet result = db.executeQuery(sql); 
                while(result.next()){
                    int id = result.getInt(1);
                    Vector row = new Vector();
                    row.addElement(result.getString("id_user"));
                    row.addElement(result.getString("ma_sach"));
                    row.addElement(result.getString("ngay_muon"));
                    row.addElement(result.getString("so_luong"));
                    row.addElement(db.getSoLuongSachConMuon(id));
                    row.addElement(result.getString("tien_coc"));
                    if(result.getInt("trang_thai")==0 && 
                        db.getSoLuongSachConMuon(id)==result.getInt("so_luong"))
                    row.addElement("Chưa trả");
                else if(result.getInt(8)==1)
                    row.addElement("Đã trả");
                else
                    row.addElement("Chưa trả hết");                
                data.add(row);
    //                row.addElement(result.getString(8));
                   // System.out.println("row "+result.getString(2));
                }
        }else if (jComboBox1.getSelectedItem().equals("Trả")){
            cols.addElement("Ngày mượn");
            cols.addElement("Ngày trả");
            cols.addElement("Số lượng");
            cols.addElement("Số tiền trả");
            sql += "id_user, ma_sach, ngay_muon, ngay_tra, tra.so_luong, so_tien from muon,tra "
                    + "Where tra.id_muon = muon.id " + sql1 + "order by ngay_muon";
                    System.out.println(sql);
                ResultSet result = db.executeQuery(sql); 
                while(result.next()){
                    Vector row = new Vector();
                    row.addElement(result.getString(1));
                    row.addElement(result.getString(2));
                    row.addElement(result.getString(3));
                    row.addElement(result.getString(4));
                    row.addElement(result.getString(5));
                    row.addElement(result.getString(6));
                data.add(row);
                }
        }else{
            cols.addElement("Ngày");
            cols.addElement("Số lượng");
            cols.addElement("Ghi chú");
            sql += "id_user, ma_sach, "
                    + "CASE" +
                    "        WHEN tra.so_luong > 0 THEN ngay_tra\n" +
                    "        ELSE ngay_muon\n" +
                    "    END AS C, "
                    + "CASE" +
                    "        WHEN tra.so_luong > 0 THEN tra.so_luong\n" +
                    "        ELSE muon.so_luong\n" +
                    "    END AS A, "
                    + "CASE" +
                    "        WHEN tra.so_luong > 0 THEN 1\n" +
                    "        ELSE 0\n" +
                    "    END AS B "
                    + ", ngay_muon, muon.so_luong "
                    + "from muon LEFT JOIN tra on muon.id=tra.id_muon "
                    + "Where 1 " + sql1 + "order by ngay_muon, ngay_tra";
                    System.out.println(sql);
                ResultSet result = db.executeQuery(sql); 
                while(result.next()){
                    Vector row = new Vector();
                    row.addElement(result.getString(1));
                    row.addElement(result.getString(2));
                    row.addElement(result.getString(3));
                    row.addElement(result.getString(4));
                    if (result.getInt(5)==1){
                        row.addElement("Trả");
                        //Nếu hàng chưas thông tin trả thì thêm 1 hàng mượn vào hiện thị
                        Vector row1 = new Vector();
                        row1.addElement(result.getString(1));
                        row1.addElement(result.getString(2));
                        row1.addElement(result.getString(6));
                        row1.addElement(result.getString(7));
                        row1.addElement("Mượn");
                        if (!data.contains(row1))
                            data.add(row1);
                    }
                    else
                        row.addElement("Mượn");
                    data.add(row);
                }
        }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbSach.setModel(new DefaultTableModel(data,cols));
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etMaso;
    private javax.swing.JTextField etMathanhvien;
    private javax.swing.JTextField etTennguoimuon;
    private javax.swing.JTextField etTensach;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSach;
    // End of variables declaration//GEN-END:variables

    @Override
    protected int tinhTien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
