/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import pac1.DonMuon;
import pac1.DonTra;
import pac1.Sach;
import pac1.User;
import util.DataUtil;
import util.Utils;

/**
 *
 * @author Trang
 */
public abstract class MyPanel extends javax.swing.JPanel {
    DataUtil db;
    Utils util;
    protected LinkedList<Sach> book = new LinkedList<>();
    protected LinkedList<User> user = new LinkedList<>();
    protected LinkedList<DonMuon> muon = new LinkedList<>();
    protected LinkedList<DonTra> tra = new LinkedList<>();
    /**
     * Creates new form MyPanel
     */
    public MyPanel() {
        initComponents();
        util = new Utils();
        db = new DataUtil();
        updateDatabase();
    }
    
    protected void updateDatabase(){
        book = db.getListSach("SELECT * FROM book ");
        user = db.getListUser("SELECT * FROM user ");
        muon = db.getListMuon();
        tra = db.getListTra();
    }

    protected abstract void loadData();
    protected abstract int tinhTien();
    
    protected DonMuon getDonMuon(String maSach, String maThanhVien, String ngayMuon){
        for (DonMuon m : muon){
            if (m.getMaSach().equals(maSach) && m.getMaThanhVien().equals(maThanhVien) 
                    && m.getNgayMuon().equals(ngayMuon) && m.getTrangThai()==0){
                return m;
            }
        }
        return null;
    }
    protected DonTra getDonTra(int idMuon, String ngayTra){
        for (DonTra t : tra){
            if (t.getIdMuon()== (idMuon) && t.getNgayTra().equals(ngayTra) ){
                return t;
            }
        }
        return null;
    }
    protected Sach getSach(String maSach){
        for (Sach m : book){
            if (m.getMasach().equals(maSach)){
                return m;
            }
        }
        return null;
    }
    protected User getUser(String mathanhvien){
        for (User m : user){
            if (m.getManguoidung().equals(mathanhvien)){
                return m;
            }
        }
        return null;
    }
    
      protected boolean checkSoLuong(int soluong){
                 if(soluong<=0){
                     JOptionPane.showMessageDialog(this, "Phải nhập số lượng là dương");
                    return false;
                 }
//                 else if(soluong>book.get(kiemtra).getSoluong()){
//                      JOptionPane.showMessageDialog(this, "Số sách hiện tại chỉ còn "+book.get(kiemtra).getSoluong());
//                    return false;
//                 }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
