/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import pac1.Sach;
import pac1.User;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;
import pac1.DonMuon;
import pac1.DonTra;
import util.DataUtil;
import static util.DataUtil.conn;

/**
 *
 * @author sony
 */
public class Tra extends MyPanel {
    /**
     * Creates new form muon
     */
    public Tra() {
        super();
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etMaso = new javax.swing.JTextField();
        etTensach = new javax.swing.JTextField();
        etMathanhvien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        etTennguoimuon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Ngaymuon = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        Ngaytra = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        etTongtien = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        etTienngay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        etSoluong = new javax.swing.JTextField();
        etTiencoc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý trả");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã số sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã thành viên");

        etMaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                etMasoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etMasoKeyReleased(evt);
            }
        });

        etTensach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etTensachKeyReleased(evt);
            }
        });

        etMathanhvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etMathanhvienKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tên người mượn");

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Mã sách", "Mã người mượn", "Ngày mượn", "Ngày trả", "Giá ngày", "Số lượng", "Tổng tiền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSach);
        if (tbSach.getColumnModel().getColumnCount() > 0) {
            tbSach.getColumnModel().getColumn(0).setResizable(false);
            tbSach.getColumnModel().getColumn(1).setResizable(false);
            tbSach.getColumnModel().getColumn(2).setResizable(false);
            tbSach.getColumnModel().getColumn(3).setResizable(false);
            tbSach.getColumnModel().getColumn(4).setResizable(false);
            tbSach.getColumnModel().getColumn(5).setResizable(false);
            tbSach.getColumnModel().getColumn(6).setResizable(false);
            tbSach.getColumnModel().getColumn(7).setResizable(false);
            tbSach.getColumnModel().getColumn(8).setResizable(false);
        }

        etTennguoimuon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etTennguoimuonKeyReleased(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Ngaymuon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NgaymuonPropertyChange(evt);
            }
        });

        jLabel10.setText("Ngày trả");

        Ngaytra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NgaytraPropertyChange(evt);
            }
        });

        jLabel11.setText("Ngày mượn");

        jLabel12.setText("Tổng tiền:");

        etTongtien.setText("0");

        jLabel13.setText("Tiền mượn/1ngày:");

        etTienngay.setText("200");
        etTienngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etTienngayKeyReleased(evt);
            }
        });

        jLabel7.setText("Số lượng");

        etSoluong.setText("1");
        etSoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etSoluongKeyReleased(evt);
            }
        });

        jLabel5.setText("Đã đặt cọc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etMaso)
                    .addComponent(etTennguoimuon)
                    .addComponent(etTensach)
                    .addComponent(etMathanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ngaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ngaytra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etTienngay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(etTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(etSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etTiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(519, 519, 519)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etTiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(etTienngay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(etTongtien)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etMaso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(etTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etMathanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(etTennguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//         db = new DataUtil();
        int check =0;
        String masach = etMaso.getText().toUpperCase();
        String mathanhvien = etMathanhvien.getText().toUpperCase();
        
        //format định dạng ngày
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String ngaymuon,ngaytra;
        try{
            ngaymuon = format1.format(Ngaymuon.getCalendar().getTime());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Bạn phải nhập ngày mượn");
            return;
        }
        ngaytra = format1.format(Ngaytra.getCalendar().getTime());
        
        //check input số lượng và số tiền ngày có đúng kiểu định dạng không
        try{
            int soluong = Integer.parseInt(etSoluong.getText());
            if(!checkSoLuong(soluong))
                return;
       }catch(NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Định dạng số lượng không phải là kiểu số");
                return;
        }
        
        try{
                int tienngay = Integer.parseInt(etTienngay.getText());
                if(!checkSoLuong(tienngay))
                    return;
            }catch(NumberFormatException | HeadlessException e){
                JOptionPane.showMessageDialog(this, "Định dạng tiền ngày không phải là kiểu số");
                return;
            } 
        //Kiểm tra đầu vào mã sách
        if(getSach(masach)!=null){
            check ++;
        } 
        //Kiểm tra đầu vào user
        if(getUser(mathanhvien)!=null)
                check ++;
        
        if(check==2){
            DonMuon m = getDonMuon(masach, mathanhvien, ngaymuon);
            if (m!=null){
                int sotien = Integer.parseInt(etTongtien.getText());
                int soluong = Integer.parseInt(etSoluong.getText());
                int soSachCon = db.getSoLuongSachConMuon(m.getId());
                int trangthai = 0;
                if(soluong < soSachCon){
                    trangthai=0;
                }else if(soluong == soSachCon){
                    trangthai=1;
                }else{
                    JOptionPane.showMessageDialog(this, "Người dùng chỉ đang mượn "+soSachCon+ " quyển.");
                    etSoluong.setText(soSachCon+"");
                    return;
                }
                String sql = "UPDATE muon SET trang_thai="+trangthai+
                        " WHERE id="+m.getId()+"";  //update vào bảng mượn
                DonTra t = getDonTra(m.getId(), ngaytra);
                if(t!=null) // kiểm tra xem ngày hôm đó đã trả quyển nào chưa
                {
                    int sotienupdate = sotien+t.getSoTien();
                    int soluongupdate;
                    soluongupdate = soluong+t.getSoLuong();
                    String sql1 = "UPDATE tra SET so_luong="+soluongupdate+
                        ",so_tien = "+sotienupdate+" WHERE id="+t.getId()+"";
                    try {
                        db.executeUpdate(sql);
                        db.executeUpdate(sql1);
                        JOptionPane.showMessageDialog(this,m.getMaThanhVien()+ " đã trả thành công "+soluong+" quyển.");
                        } catch (Exception e) {
                            System.out.println("loi");
                            e.printStackTrace();
                    }
                }
                else{
                    String sql1 = "Insert into tra(id_muon, ngay_tra, so_luong, so_tien) "
                        + "VALUES ("+m.getId()+",'"+ngaytra+"',"+soluong+","+sotien+")";
                    try {
                            db.executeUpdate(sql);
                            db.executeUpdate(sql1);
                            JOptionPane.showMessageDialog(this,m.getMaThanhVien()+ " đã trả thành công "+soluong+" quyển.");
                            } catch (Exception e) {
                                System.out.println("loi");
                                e.printStackTrace();
                        }
                    }
                if(trangthai==1){ //nếu khách trả hết tất cả sách thì in ra cần thanh toán ntn
                            int thanhToan = sotien- m.getTiencoc();
                            if (thanhToan>0)
                                JOptionPane.showMessageDialog(this, "Khách hàng cần trả: "+thanhToan+" đồng");
                            else
                                JOptionPane.showMessageDialog(this, "Cần trả lại khách hàng: "+ (-thanhToan)+" đồng");
                        }
                        updateDatabase();
                    loadData();
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin đơn mượn. Xin vui lòng kiểm tra lại");

            }
        }
        else
            JOptionPane.showMessageDialog(this, "Bạn đã nhập sai hoặc thiếu thông tin. Xin vui lòng kiểm tra lại");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void etMasoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMasoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_etMasoKeyPressed

    private void etMasoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMasoKeyReleased
        // TODO add your handling code here:
        String masach = etMaso.getText().toUpperCase();
        etTensach.setText("");
        for(int i=0;i<book.size();i++){
            if(book.get(i).getMasach().toUpperCase().equals(masach)){
                etTensach.setText(book.get(i).getTensach());
//                tinhTien();
                updateDonMuon();
                break;
            }
        }
    }//GEN-LAST:event_etMasoKeyReleased

    private void etMathanhvienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etMathanhvienKeyReleased
        // TODO add your handling code here:
        String mathanhvien = etMathanhvien.getText().toUpperCase();
        etTennguoimuon.setText("");
        for(int i=0;i<user.size();i++){
            if(user.get(i).getManguoidung().toUpperCase().equals(mathanhvien)){
                etTennguoimuon.setText(user.get(i).getTennguoidung());
//                tinhTien();
                updateDonMuon();
                break;
            }
        }
    }//GEN-LAST:event_etMathanhvienKeyReleased

    private void etTensachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTensachKeyReleased
        // TODO add your handling code here:
        String tensach = etTensach.getText().toUpperCase();
        etMaso.setText("");
        for(int i=0;i<book.size();i++){
            if(book.get(i).getTensach().toUpperCase().equals(tensach)){
                etMaso.setText(book.get(i).getMasach());
//                tinhTien();
                updateDonMuon();
                break;
            }
        }
    }//GEN-LAST:event_etTensachKeyReleased

    private void etTennguoimuonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTennguoimuonKeyReleased
        // TODO add your handling code here:
         String nguoimuon = etTennguoimuon.getText().toUpperCase();
        etMathanhvien.setText("");
        for(int i=0;i<user.size();i++){
            if(user.get(i).getTennguoidung().toUpperCase().equals(nguoimuon)){
                etMathanhvien.setText(user.get(i).getManguoidung());
//                tinhTien();
                updateDonMuon();
                break;
            }
        }
    }//GEN-LAST:event_etTennguoimuonKeyReleased

    private void NgaymuonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NgaymuonPropertyChange
        // TODO add your handling code here:
        
        if(Ngaymuon.getCalendar()!=null){
//                  Calendar cal;
////         Ngaytra.setCalendar(Ngaymuon.getCalendar());
//         cal = Ngaymuon.getCalendar();
//         cal.add(Calendar.DATE, 7);
//         Ngaytra.setCalendar(cal);
            updateDonMuon();
        }
        

    }//GEN-LAST:event_NgaymuonPropertyChange

    private void NgaytraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NgaytraPropertyChange
        // TODO add your handling code here:
        if(Ngaytra.getCalendar()!=null || Ngaymuon.getCalendar()!=null){
            int soNgay=util.hieu2Ngay(Ngaymuon.getCalendar(), Ngaytra.getCalendar());
            if (soNgay<0){
                JOptionPane.showMessageDialog(this, "Ngày trả phải sau ngày mượn");
                Ngaytra.setCalendar(Ngaymuon.getCalendar());
            }
            tinhTien();
        }else{
            Ngaytra.setCalendar(Calendar.getInstance());
        }
    }//GEN-LAST:event_NgaytraPropertyChange

    private void etTienngayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTienngayKeyReleased
        // TODO add your handling code here:
        tinhTien();
    }//GEN-LAST:event_etTienngayKeyReleased

    private void etSoluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etSoluongKeyReleased
        // TODO add your handling code here:
         tinhTien();
    }//GEN-LAST:event_etSoluongKeyReleased
    
    @Override
    protected void loadData(){
        String sql = "SELECT * FROM muon order by id DESC";
        
        Vector data = new Vector();
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("ID User");
        cols.addElement("Mã sách");
        cols.addElement("Ngày mượn");
//        cols.addElement("Ngày trả dự kiến");
        cols.addElement("Số lượng mượn");
        cols.addElement("Số lượng chưa trả");
        cols.addElement("Tiền cọc");
        cols.addElement("Số tiền mượn đã trả");
        cols.addElement("Trạng thái");
//        cols.addElement("Trạng thái");
        try {
            ResultSet result = db.executeQuery(sql); 
            while(result.next()){
                Vector row = new Vector();
                int id = result.getInt(1);
                row.addElement(result.getString(1));
                row.addElement(result.getString(2));
                row.addElement(result.getString(3));
                row.addElement(result.getString(4));
                row.addElement(result.getString(6));
                row.addElement(db.getSoLuongSachConMuon(id));
                row.addElement(result.getString(7));
                row.addElement(db.getSoTienMuonDaTra(id));
                if(result.getInt(8)==0 && 
                        db.getSoLuongSachConMuon(id)==result.getInt(6))
                    row.addElement("Chưa trả");
                else if(result.getInt(8)==1)
                    row.addElement("Đã trả");
                else
                    row.addElement("Chưa trả hết");                
                data.add(row);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbSach.setModel(new DefaultTableModel(data,cols));
    }
    @Override
    protected int tinhTien(){
        if(etMaso!=null && etMathanhvien !=null && Ngaymuon.getCalendar()!=null){
            int songay = util.hieu2Ngay(Ngaymuon.getCalendar(), Ngaytra.getCalendar());
            int sum=0;
            try{
            int tienngay = Integer.parseInt(etTienngay.getText());
            int soluong = Integer.parseInt(etSoluong.getText());
            sum = tienngay*songay*soluong;
            etTongtien.setText(sum+"");
            }catch(NumberFormatException | HeadlessException e){
                    return 0;
            } 
            return sum;
        }
        return 0;
    }
    
    private void updateDonMuon(){
        if(etMaso!=null && etMathanhvien !=null && Ngaymuon.getCalendar()!=null && etSoluong!=null){
            System.out.println("1");
             SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
             String ngaymuon = format1.format(Ngaymuon.getCalendar().getTime());
             String masach = etMaso.getText().toUpperCase();
            String mathanhvien = etMathanhvien.getText().toUpperCase();
            DonMuon m = getDonMuon(masach,mathanhvien,ngaymuon);
            if (m!=null){
                System.out.println("2");
                int songay = util.hieu2Ngay(Ngaymuon.getCalendar(), Ngaytra.getCalendar());
//                System.out.println(m.getTienNgay());
                
//                etTienngay.setText(m.getTienNgay()+"");
                etSoluong.setText(db.getSoLuongSachConMuon(m.getId())+"");
               // etSoluong.setText((m.getSoLuong()-m.getSoluongdatra(m.getId()))+"");
                int sum = Integer.parseInt(etTienngay.getText())*songay*Integer.parseInt(etSoluong.getText());
                etTongtien.setText(sum+"");
                etTiencoc.setText(""+getDonMuon(masach,mathanhvien,ngaymuon).getTiencoc());

            }else{
                etTongtien.setText(0+"");
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Ngaymuon;
    private com.toedter.calendar.JDateChooser Ngaytra;
    private javax.swing.JTextField etMaso;
    private javax.swing.JTextField etMathanhvien;
    private javax.swing.JTextField etSoluong;
    private javax.swing.JTextField etTennguoimuon;
    private javax.swing.JTextField etTensach;
    private javax.swing.JLabel etTiencoc;
    private javax.swing.JTextField etTienngay;
    private javax.swing.JLabel etTongtien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSach;
    // End of variables declaration//GEN-END:variables
}
